In [1]:
# Writen by liupu -- 2019.4.13
# Need to install numpy, sklearn
import numpy as np
from sklearn.datasets import load_iris

In [2]:
iris=load_iris()
data=iris.data      #data_x
target=iris.target  #data_y
labels=iris.feature_names #feature_name

In [3]:
print(labels)
print(data.shape)
print(data[:10])
print(target.shape)
print(target)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
(150, 4)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]
(150,)
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [4]:
train_y = np.append(np.append(target[:40], target[50:90]), target[100:140])
train_x = np.append(np.append(data[:40,], data[50:90,], axis=0), data[100:140,], axis=0)
test_y = np.append(np.append(target[40:50], target[90:100]), target[140:150])
test_x = np.append(np.append(data[40:50], data[90:100], axis=0), data[140:150], axis=0)

In [5]:
print(train_x.shape, train_y.shape)
print(test_x.shape, test_y.shape)
print(test_y)

(120, 4) (120,)
(30, 4) (30,)
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2]


In [6]:
class Linear():
    def __init__(self):
        self._w = None                 # _w = [ feature_num, bias ]
        self._x = None
        self._y = None
        self._feature_num = 0
    
    def softmax(x):
        return 
    
    def fit(self, x, y, optimizer="square", learning_rate=0.001, epoch=1, log=True):
        assert len(x.shape) == 2
        assert len(y.shape) == 1
        assert x.shape[0] == y.shape[0]
        self._feature_num = x.shape[1]
        if self._w == None:
            self._w = np.random.normal(0.1, 1, size=self._feature_num+1)    # _w = [ feature_num, bias ], ^y = Xw
        self._x = np.append(x, np.tile(1, [x.shape[0],1]), axis=1)
        self._y = y
        if optimizer == "square":
            self._w = np.matmul(np.linalg.pinv(self._x), self._y)
        elif optimizer == "sgd":
            if log == True:
                print("Log is working on...")
                print("The learning_rate is now %f. Start..."%learning_rate)
            for j in range(epoch):
                print("********************* Epoch %d **********************"%j)
                for i, item in enumerate(self._x):
                    loss = 1/2*(self._y[i]-np.matmul(item.T, self._w))**2
                    gradient = -1*item*(self._y[i]-np.matmul(item.T, self._w))
                    self._w -= learning_rate * gradient
                    if i:
                        print("Iter : %d, Loss : %f"%(i+1,loss))
            
    
    def predict(self, x):
        assert len(x.shape) == 2
        assert self._feature_num == x.shape[1]
        expand_x = np.append(x, np.tile(1, [x.shape[0],1]), axis=1)
        return np.matmul(expand_x, self._w)          

In [7]:
linear = Linear()
linear.fit(x=train_x, y=train_y, optimizer="sgd", epoch=5)
y = linear.predict(test_x)
yy = linear.predict(train_x)

Log is working on...
The learning_rate is now 0.001000. Start...
********************* Epoch 0 **********************
Iter : 2, Loss : 3.064480
Iter : 3, Loss : 3.017469
Iter : 4, Loss : 3.352576
Iter : 5, Loss : 3.075749
Iter : 6, Loss : 4.170618
Iter : 7, Loss : 2.924614
Iter : 8, Loss : 2.361111
Iter : 9, Loss : 2.018982
Iter : 10, Loss : 1.672263
Iter : 11, Loss : 1.795022
Iter : 12, Loss : 2.156456
Iter : 13, Loss : 1.120772
Iter : 14, Loss : 0.929126
Iter : 15, Loss : 0.721578
Iter : 16, Loss : 1.781896
Iter : 17, Loss : 1.126319
Iter : 18, Loss : 1.038265
Iter : 19, Loss : 1.145986
Iter : 20, Loss : 1.201195
Iter : 21, Loss : 0.815442
Iter : 22, Loss : 1.087776
Iter : 23, Loss : 0.430728
Iter : 24, Loss : 1.162567
Iter : 25, Loss : 1.328444
Iter : 26, Loss : 0.459840
Iter : 27, Loss : 0.792661
Iter : 28, Loss : 0.348324
Iter : 29, Loss : 0.212191
Iter : 30, Loss : 0.580098
Iter : 31, Loss : 0.440116
Iter : 32, Loss : 0.251676
Iter : 33, Loss : 0.315960
Iter : 34, Loss : 0.170620

In [8]:
print(y)
print((y+0.5).astype(int))              # 0.0-0.49 ~= 0, 0.50-0.99 ~= 1
print(test_y)

[-0.78485317 -0.81609577 -0.48272682 -0.34425617 -0.24859888 -0.73234928
 -0.61459807 -0.57236835 -0.88510999 -0.85985246  1.39504518  1.34838703
  0.86310966  0.74667257  1.28048724  1.23393876  1.27220189  0.93969628
  0.59618146  1.16359936  2.36765018  1.76980369  2.21657542  2.46523593
  2.58718519  1.96764627  1.66686474  1.90576224  2.66229415  2.17002694]
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 2 2 2 2 3 2 2 2 3 2]
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2]


In [9]:
print(yy)
print((yy+0.5).astype(int))              # 0.0-0.49 ~= 0, 0.50-0.99 ~= 1
print(train_y)

[-0.86813781 -0.88790178 -0.72559091 -0.53643517 -0.75084844 -0.59966401
 -0.4251012  -0.75124993 -0.51946298 -0.85389706 -0.96606469 -0.51707268
 -0.8815449  -0.693575   -1.39768303 -0.80539045 -0.88873545 -0.79354
 -0.95346058 -0.61226812 -0.93053299 -0.57400499 -0.71610109 -0.50021016
 -0.3002691  -0.82432076 -0.52978646 -0.87682465 -0.98542718 -0.50878733
 -0.6260767  -0.9258731  -0.73341441 -0.93761388 -0.77929925 -1.04072285
 -1.26422445 -0.74449155 -0.55539617 -0.83220462  0.76473197  1.18052224
  1.02848552  1.07156753  1.02649671  1.4526708   1.51694513  0.86396194
  0.83268107  1.46210025  0.78220427  1.29582279  0.40666596  1.38432021
  0.91954944  0.75445781  1.75549045  0.82251657  0.97908489  0.84181871
  2.02589271  0.76751272  1.29620565  1.19878993  0.77778689  0.79907783
  0.85357053  1.37552371  1.395337    0.43352944  0.81417087  0.66730521
  0.82717647  1.83087261  1.91739984  1.65160817  1.04585919  0.7130014
  1.3172234   1.14423687  3.12780755  2.21657542  2.000