In [1]:
# Writen by liupu -- 2019.4.10
# Need to install numpy, sklearn
import numpy as np
from sklearn.datasets import load_iris

In [2]:
iris=load_iris()
data=iris.data      #data_x
target=iris.target  #data_y
labels=iris.feature_names #feature_name

In [3]:
print(labels)
print(data.shape)
print(data[:10])
print(target.shape)
print(target)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
(150, 4)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]
(150,)
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [4]:
train_y = np.append(np.append(target[:40], target[50:90]), target[100:140])
train_x = np.append(np.append(data[:40,], data[50:90,], axis=0), data[100:140,], axis=0)
test_y = np.append(np.append(target[40:50], target[90:100]), target[140:150])
test_x = np.append(np.append(data[40:50], data[90:100], axis=0), data[140:150], axis=0)

In [5]:
print(train_x.shape, train_y.shape)
print(test_x.shape, test_y.shape)
print(test_y)

(120, 4) (120,)
(30, 4) (30,)
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2]


In [6]:
class Linear():
    def __init__(self):
        self._w = None                 # _w = [ feature_num, bias ]
        self._x = None
        self._y = None
        self._feature_num = 0
    
    def fit(self, x, y, optimizer="square", log=True):
        assert len(x.shape) == 2
        assert len(y.shape) == 1
        assert x.shape[0] == y.shape[0]
        self._feature_num = x.shape[1]
        self._w = np.random.normal(0.1, 1, size=self._feature_num+1)    # _w = [ feature_num, bias ], ^y = Xw
        self._x = np.append(x, np.tile(1, [x.shape[0],1]), axis=1)
        self._y = y
        if optimizer == "square":
            self._w = np.matmul(np.linalg.pinv(self._x), self._y)
        elif optimizer == "sgd":
            pass
    
    def predict(self, x):
        assert len(x.shape) == 2
        assert self._feature_num == x.shape[1]
        expand_x = np.append(x, np.tile(1, [x.shape[0],1]), axis=1)
        return np.matmul(expand_x, self._w)          

In [7]:
linear = Linear()
linear.fit(x=train_x, y=train_y)
y = linear.predict(test_x)

In [8]:
print(y)
print((y+0.5).astype(int))              # 0.0-0.49 ~= 0, 0.50-0.99 ~= 1
print(test_y)

[-3.73771047e-02  4.22358356e-02  9.36225264e-04  2.00636085e-01
  1.68284983e-01  2.30971444e-02 -1.89072479e-02  3.03078180e-04
 -7.60124240e-02 -5.85582693e-02  1.23621023e+00  1.30518989e+00
  1.07841827e+00  8.95443169e-01  1.21486118e+00  1.14778073e+00
  1.19916320e+00  1.15480517e+00  8.45015834e-01  1.17120794e+00
  2.01055593e+00  1.78800120e+00  1.74728796e+00  2.03014881e+00
  2.08877063e+00  1.84622940e+00  1.64701942e+00  1.72291644e+00
  1.97389168e+00  1.68020750e+00]
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2]
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2]
