In [1]:
# Writen by liupu -- 2019.4.13
# Need to install numpy, sklearn
import numpy as np
from sklearn.datasets import load_iris

In [2]:
iris=load_iris()
data=iris.data      #data_x
target=iris.target  #data_y
labels=iris.feature_names #feature_name

In [3]:
print(labels)
print(data.shape)
print(data[:10])
print(target.shape)
print(target)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
(150, 4)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]
(150,)
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [4]:
train_y = np.append(np.append(target[:40], target[50:90]), target[100:140])
train_x = np.append(np.append(data[:40,], data[50:90,], axis=0), data[100:140,], axis=0)
test_y = np.append(np.append(target[40:50], target[90:100]), target[140:150])
test_x = np.append(np.append(data[40:50], data[90:100], axis=0), data[140:150], axis=0)

In [5]:
print(train_x.shape, train_y.shape)
print(test_x.shape, test_y.shape)
print(test_y)

(120, 4) (120,)
(30, 4) (30,)
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2]


In [10]:
class Linear():
    def __init__(self):
        self._w = None                 # _w = [ feature_num, bias ]
        self._x = None
        self._y = None
        self._feature_num = 0
    
    def sigmoid(self, x):
        return 1 / (1+np.exp(-x))
    
    def get_gradient(self, x, y):
        xTw = np.matmul(x.T, self._w)
        sig = self.sigmoid(xTw)
        return sig * (sig-1) * (y-sig) * x
    
    def fit(self, x, y, optimizer="square", learning_rate=0.001, epoch=1, log=True):
        assert len(x.shape) == 2
        assert len(y.shape) == 1
        assert x.shape[0] == y.shape[0]
        self._feature_num = x.shape[1]
        if self._w == None:
            self._w = np.random.normal(0.1, 1, size=self._feature_num+1)    # _w = [ feature_num, bias ], ^y = Xw
        self._x = np.append(x, np.tile(1, [x.shape[0],1]), axis=1)
        self._y = y
        if optimizer == "sgd":
            if log == True:
                print("Log is working on...")
                print("The learning_rate is now %f. Start..."%learning_rate)
            for j in range(epoch):
                print("********************* Epoch %d **********************"%j)
                for i, item in enumerate(self._x):
                    loss = 1/2*(self._y[i]-np.matmul(item.T, self._w))**2
                    gradient = self.get_gradient(item, self._y[i])
                    self._w -= learning_rate * gradient
                    if i:
                        print("Iter : %d, Loss : %f"%(i+1,loss))
            
    
    def predict(self, x):
        assert len(x.shape) == 2
        assert self._feature_num == x.shape[1]
        expand_x = np.append(x, np.tile(1, [x.shape[0],1]), axis=1)
        return np.matmul(expand_x, self._w)          

In [11]:
linear = Linear()
linear.fit(x=train_x, y=train_y, optimizer="sgd", epoch=5)
y = linear.predict(test_x)
yy = linear.predict(train_x)

Log is working on...
The learning_rate is now 0.001000. Start...
********************* Epoch 0 **********************
Iter : 2, Loss : 4.607177
Iter : 3, Loss : 5.080697
Iter : 4, Loss : 3.600822
Iter : 5, Loss : 5.944798
Iter : 6, Loss : 5.667148
Iter : 7, Loss : 4.630696
Iter : 8, Loss : 4.940425
Iter : 9, Loss : 3.383113
Iter : 10, Loss : 4.172129
Iter : 11, Loss : 6.490961
Iter : 12, Loss : 3.931700
Iter : 13, Loss : 4.320335
Iter : 14, Loss : 4.897478
Iter : 15, Loss : 10.669149
Iter : 16, Loss : 8.938457
Iter : 17, Loss : 8.379778
Iter : 18, Loss : 5.960245
Iter : 19, Loss : 6.139152
Iter : 20, Loss : 5.901392
Iter : 21, Loss : 4.642438
Iter : 22, Loss : 5.716567
Iter : 23, Loss : 7.509892
Iter : 24, Loss : 3.876936
Iter : 25, Loss : 2.486368
Iter : 26, Loss : 3.653532
Iter : 27, Loss : 4.325479
Iter : 28, Loss : 5.500212
Iter : 29, Loss : 5.932040
Iter : 30, Loss : 3.358913
Iter : 31, Loss : 3.394834
Iter : 32, Loss : 5.815024
Iter : 33, Loss : 6.638843
Iter : 34, Loss : 8.44847

In [12]:
print(y)
print((y+0.5).astype(int))              # 0.0-0.49 ~= 0, 0.50-0.99 ~= 1
print(test_y)

[6.59147748 5.14255612 5.6816764  6.18061763 6.01831599 5.84296151
 6.4463269  5.75090666 6.74955044 6.27179126 1.85900025 2.55195911
 2.81041953 2.73886319 2.37024271 2.68740516 2.63034081 3.03457297
 3.47842539 2.71022975 1.92664549 2.90335075 1.30954458 1.63306411
 1.93812302 2.4516964  1.87355462 2.17690862 1.88201283 1.62670704]
[7 5 6 6 6 6 6 6 7 6 2 3 3 3 2 3 3 3 3 3 2 3 1 2 2 2 2 2 2 2]
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2]


In [9]:
print(yy)
print((yy+0.5).astype(int))              # 0.0-0.49 ~= 0, 0.50-0.99 ~= 1
print(train_y)

[-0.86813781 -0.88790178 -0.72559091 -0.53643517 -0.75084844 -0.59966401
 -0.4251012  -0.75124993 -0.51946298 -0.85389706 -0.96606469 -0.51707268
 -0.8815449  -0.693575   -1.39768303 -0.80539045 -0.88873545 -0.79354
 -0.95346058 -0.61226812 -0.93053299 -0.57400499 -0.71610109 -0.50021016
 -0.3002691  -0.82432076 -0.52978646 -0.87682465 -0.98542718 -0.50878733
 -0.6260767  -0.9258731  -0.73341441 -0.93761388 -0.77929925 -1.04072285
 -1.26422445 -0.74449155 -0.55539617 -0.83220462  0.76473197  1.18052224
  1.02848552  1.07156753  1.02649671  1.4526708   1.51694513  0.86396194
  0.83268107  1.46210025  0.78220427  1.29582279  0.40666596  1.38432021
  0.91954944  0.75445781  1.75549045  0.82251657  0.97908489  0.84181871
  2.02589271  0.76751272  1.29620565  1.19878993  0.77778689  0.79907783
  0.85357053  1.37552371  1.395337    0.43352944  0.81417087  0.66730521
  0.82717647  1.83087261  1.91739984  1.65160817  1.04585919  0.7130014
  1.3172234   1.14423687  3.12780755  2.21657542  2.000